// angular-app/src/app/visualization/area-chart/area-chart.component.ts
import { Component, Input } from '@angular/core';
import { area as d3_area, curveBasis } from 'd3-shape';

export interface AreaChartItem {
  width: number;
  height: number;
  barWidth: number;
  data: any[];
  selectedItem: any;
  mouseOver: any;
}

@Component({
  selector: '[app-area-chart]',
  templateUrl: './area-chart.component.html'
})
export class AreaChartComponent {
  @Input() item: AreaChartItem;

  getAreaPath(): string {
    const area = d3_area()
      .curve(curveBasis)
      .x(d => d.x)
      .y0(d => d.y0)
      .y1(d => d.y1);
    return area(this.item.data);
  }
}

<svg:g class="area-chart">
  <svg:defs>
    <svg:mask
      id='mask-for-area-chart'
      maskUnits="userSpaceOnUse"
      maskContentUnits="userSpaceOnUse"
    >
      <svg:g app-area [d]="getAreaPath()">
      </svg:g>
    </svg:mask>
  </svg:defs>
  <svg:rect
    mask='url(#mask-for-area-chart)'
    class="area-chart"
    [attr.width.px]="item.width"
    [attr.height.px]="item.height"
  >
  </svg:rect>
  <svg:g class="hover-section">
    <svg:g *ngFor="let row of item.data">
      <svg:rect [attr.x.px]="row.x - item.barWidth"
                (mouseover)="item.mouseOver(row)"
                [attr.width.px]="item.barWidth"
                [attr.height.px]="item.height">
      </svg:rect>
    </svg:g>
  </svg:g>
  <svg:g *ngIf="item.selectedItem">
    <svg:rect
      mask='url(#mask-for-area-chart)'
      class="area-chart selected"
      [attr.x.px]="item.selectedItem.x"
      [attr.height.px]="item.height"
      [attr.width.px]="item.barWidth"
    />
  </svg:g>
</svg:g>

// react-app/src/App/Visualization/AreaChart/index.js
import React from 'react';
import {area as d3_area, curveBasis} from 'd3-shape';
import Area from "./Area";

const AreaChart = ({data, xScale, yScale, selectedItem, setSelectedItem, barWidth = 0}) => {

    // Set up an area chart generator
    const area = d3_area()
        .curve(curveBasis)
        .x(d => d.x)
        .y0(d => d.y0)
        .y1(d => d.y1);

    const onMouseOver = item => () => setSelectedItem(item);

    return (
        <g className="area-chart">
            <defs>
                <mask
                    id='mask-for-area-chart'
                    maskUnits="userSpaceOnUse"
                    maskContentUnits="userSpaceOnUse"
                >
                    <Area
                        d={area(
                            data.map(f => {
                                return {
                                    x: xScale(f.x),
                                    y0: yScale(0),
                                    y1: yScale(f.y)
                                };
                            })
                        )}
                    />
                </mask>
            </defs>
            <rect
                mask='url(#mask-for-area-chart)'
                className="area-chart"
                width={xScale.range()[1]}
                height={yScale.range()[0]}
            />
            <g className="hover-section">
                {data.map((f, i) => {
                    return (
                        <rect
                            key={`hover-section-for-${i}`}
                            onMouseOver={onMouseOver(f)}
                            x={xScale(f.x) - barWidth}
                            width={barWidth}
                            height={yScale.range()[0]}
                        />
                    );
                })}
            </g>
            {
                selectedItem && <rect
                    mask='url(#mask-for-area-chart)'
                    className="area-chart selected"
                    x={xScale(selectedItem.x)}
                    height={yScale.range()[0]}
                    width={barWidth}
                />
            }
        </g>
    )
};
export default AreaChart;
