// react-app/src/App/Visualization/index.js
import React, {useState} from 'react';
import {extent, max, range} from 'd3-array';
import {scaleLinear, scaleTime} from 'd3-scale';
import moment from 'moment';
import Axes from "./Axes";
import AreaChart from "./AreaChart";

const INCREMENT = 'days';
const N = 150;

const Visualization = ({incrementCount, selectedItem, setSelectedItem}) => {

    // Set up some constant variables for the visualization
    const width = 960;
    const height = 500;
    const margin = {
        left: 20,
        right: 20,
        bottom: 20,
        top: 20
    };

    // Retrieve the inner height and width for which we will be drawing on
    const innerHeight = height - margin.top - margin.bottom;
    const innerWidth = width - margin.left - margin.right;

    // Create a random sampling of data points, useState to ensure it isn't updated during re-renders
    const [data] = useState(
        range(N / incrementCount)
            .map(i => {
                return {
                    y: innerHeight / 2 + 150 * Math.sin(i / 5),
                    x: moment().subtract(incrementCount * i, INCREMENT)
                };
            })
    );

    // Set up an x- and y-scale
    const xScale = scaleTime()
        .range([0, innerWidth])
        .domain(extent(data, d => d.x));
    const yScale = scaleLinear()
        .range([innerHeight, 0])
        .domain([0, max(data, d => d.y)]);

    // Calculate the distance, in time, between points
    const barWidth = xScale.range()[1] - xScale(moment(xScale.domain()[1]).subtract(incrementCount, INCREMENT));

    return (
        <svg width={width} height={height}>
            <g transform={`translate(${margin.left},${margin.top})`}>
                <AreaChart data={data} xScale={xScale} yScale={yScale} barWidth={barWidth} selectedItem={selectedItem}
                           setSelectedItem={setSelectedItem}/>
                <Axes height={innerHeight} xScale={xScale}/>
            </g>
        </svg>
    )
};
export default Visualization;

// angular-app/src/app/visualization/visualization.component.ts
import { ChangeDetectorRef, Component, Input, OnChanges, OnInit } from '@angular/core';
import { AxesItem } from './axes/axes.component';
import { scaleTime, scaleLinear } from 'd3-scale';
import { extent, max, range } from 'd3-array';
import { AreaChartItem } from './area-chart/area-chart.component';
import * as moment from 'moment';

@Component({
  selector: 'app-visualization',
  templateUrl: './visualization.component.html'
})
export class VisualizationComponent implements OnInit, OnChanges {
  @Input() incrementCount: number;
  xScale = scaleTime();
  yScale = scaleLinear();
  width = 960;
  height = 500;
  margin = {
    left: 20,
    right: 20,
    bottom: 20,
    top: 20
  };
  n = 150;
  increment: moment.unitOfTime.DurationConstructor = 'days';
  data: any[];
  selectedItem = null;

  constructor(protected cdr: ChangeDetectorRef) {
  }

  get innerHeight(): number {
    return this.height - this.margin.top - this.margin.bottom;
  }

  get innerWidth(): number {
    return this.width - this.margin.left - this.margin.right;
  }

  ngOnInit(): void {
    this.data = range(this.n / this.incrementCount)
      .map(i => {
        return {
          y: innerHeight / 2 + 150 * Math.sin(i / 5),
          x: moment().subtract(this.incrementCount * i, this.increment)
        };
      });
    this.setAxisScales();
  }

  setAxisScales() {
    // Set up an x- and y-scales
    this.xScale = this.xScale
      .range([0, this.innerWidth])
      .domain(extent(this.data, d => d.x));
    this.yScale = this.yScale
      .range([this.innerHeight, 0])
      .domain([0, max(this.data, d => d.y)]);
  }

  get gTransform(): string {
    return `translate(${this.margin.left},${this.margin.top})`;
  }

  formatAxes(): AxesItem {
    return {
      xScale: this.xScale,
      yScale: this.yScale,
      height: this.innerHeight
    };
  }

  formatAreaChartItem(): AreaChartItem {
    return {
      width: this.innerWidth,
      height: this.innerHeight,
      barWidth: this.innerWidth - this.xScale(moment(this.xScale.domain()[1]).subtract(this.incrementCount, this.increment)),
      data: this.data.map(f => {
        return {
          x: this.xScale(f.x),
          y0: this.yScale(0),
          y1: this.yScale(f.y)
        };
      }),
      selectedItem: this.selectedItem,
      mouseOver: row => {
        this.selectedItem = row;
      }
    };
  }

  ngOnChanges(): void {
    setTimeout(() => {
      this.selectedItem = null;
      this.setAxisScales();
      this.cdr.detectChanges();
    }, 1);
  }
}

<svg [attr.width.px]="width" [attr.height.px]="height">
  <g [attr.transform]="gTransform">
    <g app-area-chart [item]="formatAreaChartItem()"></g>
    <g app-axes [item]="formatAxes()"></g>
  </g>
</svg>
