// react-app/src/App/index.js
import React, {useState} from 'react';
import Visualization from "./Visualization";

const App = () => {
    const [incrementCount, setIncrementCount] = useState(5);
    const [selectedItem, setSelectedItem] = useState(null);

    const onChange = d => () => {
        setSelectedItem(null);
        setIncrementCount(d);
    };

    return (
        <div className="app">
            <div className="form-group">
                <p>Please select an increment count, in days, for hover:</p>
                {[1, 2, 5, 10].map(d => {
                    return (
                        <div key={`increment-count-radio-${d}`}>
                            <input type="radio"
                                   name="increment-count"
                                   value={d}
                                   onChange={onChange(d)}
                                   checked={incrementCount === d}/>
                            {`${d} days`}
                        </div>
                    )
                })}
            </div>
            <Visualization selectedItem={selectedItem} setSelectedItem={setSelectedItem}
                           incrementCount={incrementCount}/>
        </div>
    );
};

export default App;

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  incrementCount = 5;

  private changeIncrementCount(row: number) {
    this.incrementCount = row;
  }
}

<div class="app">
  <div class="form-group">
    <p>Please select an increment count, in days, for hover:</p>
    <div *ngFor="let row of [1, 2, 5, 10]">
      <input type="radio"
             name="increment-count"
             (change)="changeIncrementCount(row)"
             value="{{row}}"
             [attr.checked]="incrementCount === row ? true: null"/>
      {{row}} days
    </div>
    <app-visualization [incrementCount]="incrementCount"></app-visualization>
  </div>
